#!/bin/bash

addScriptToPATH () {
  
  if ! command -v scripts;
  else
      echo 'export PATH=$PATH:/home/ubuntu/scripts' >> ~/.profile
  f1 
}

change_MOTD(){
    #I am not wanting the user to see that a reboot is required so he/she doesn't reboot the system
    sudo chmod -x /etc/update-motd.d/98-reboot-required

    #I also don't want the user to see any available updates. That is the job of the system admin
    sudo chmod -x /etc/update-motd.d/90-updates-available

    #What I am trying to do with this one is tell a particular user how many nodes they are running
    echo '"Welcome to your system '$(echo $USER)'. There are currently '$(find . | wc -l)'-nodes running on your account"' /etc/update-motd.d/##curto-motd

} 

customize_Vim () {
  #This installes the Solarized vim color scheme

  mkdir ~/.vim
  mkdir ~/.vim/bundle
  cd ~/.vim/bundle
  git clone git://github.com/altercation/solarized.git
  cd solarized/
  mv vim-colors-solarized/ ~/.vim/bundle/
  cd
  vim .vimrc
  i
  sytanx enable
  set background=light
  colorscheme solarized
}

printHelp() {
  if [[$1 = '-help'] || [$1 = 'help'] || [$1 = '-h'] || [$1 = 'h']]; then
  echo "Usage: passwd [options] [LOGIN]"
	echo ""
  echo "Options:"
  echo " -a, --all                        report password status on all accounts"
  echo " -d, --delete                     delete the password for the named account"
  echo " -e, --expire                     for expire the password for the named account"
  echo " -h, --help                       display this help message and exit"
  echo " -k, --keep-tokens                change password only if expired"
  echo " -i, --inactive INACTIVE          set password inactive after expiration to INACTIVE"
  echo " -l, --lock                       lock the password of the named account"
  echo " -n, --mindays MIN_DAYS           set minimum number of days before password change to MIN_DAYS"
  echo " -q, --quiet                      quiet mode"
  echo " -r, --repository REPOSITORY      change password in REPOSITY repository"
  echo " -R, --root CHROOT_DIR            directory to chroot into"
  echo " -S, --status                  report password status on the named account"
  echo " -u, --unlock                  unlock the password of the named account"
  echo " -w, --warndays WARN_DAYS      set expiration warning days to WARN_DAYS"
  echo " -x, --maxdays MAX_DAYS        set maximum number of days before password change to MAX_DAYS"
  # call printHelp
f1
}
 
 
motdFromInternet() {
  sudo apt install fortune-mod cowsay
  Y
}

addScriptToPATH
change_MOTD
printHelp
motdFromInternet
